# Generated by Django 5.0.6 on 2024-05-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board', '0011_alter_task_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='board',
            new_name='board_id',
        ),
    ]
