# Generated by Django 5.0.6 on 2024-05-24 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board', '0014_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
    ]
